codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        # ต้องการค่า coverage ขั้นต่ำ 80%
        target: 80%
        # ยอมให้ลดลงมากสุดกี่เปอร์เซ็นต์จากค่าเดิม
        threshold: 1%
        # ถ้าค่าต่ำกว่าเป้า ให้ตั้งเป็น failed
        if_not_met: error
        # ต้องการใช้กับการอัพเดททั้งโปรเจค
        if_ci_failed: error
    
    # สำหรับไฟล์ที่เปลี่ยนแปลงใน PR
    patch:
      default:
        target: 80%
        if_not_met: error

    # เช็คว่า PR มีการทดสอบที่เหมาะสมหรือไม่
    changes:
      default:
        if_not_met: error

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # แสดงคอมเม้นต์เสมอ
  require_base: no
  require_head: yes