name: majot
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" #^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  signals: ^6.0.2
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  
  # Authentication
  google_sign_in: ^6.3.0
  local_auth: ^2.1.0
  
  # Data & Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  
  # Networking
  dio: ^5.4.2
  connectivity_plus: ^6.0.1
  
  # Routing
  go_router: ^15.0.5
  
  # Utils
  intl: any
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_gen: ^5.10.0
  mockito: ^5.4.6
  encrypt: ^5.0.1
  
  # Database
  sqflite: ^2.3.2
  path_provider: ^2.1.3
  drift: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Linting & Analysis
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  drift_dev: ^2.15.0
  riverpod_generator: ^2.5.0

flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/images/