name: CD

on:
  push:
    tags:
      - 'v*.*.*'   # semantic versioning

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - run: flutter build apk --release    # หรือ ios :contentReference[oaicite:11]{index=11}
      - run: |
          mkdir release
          cp build/app/outputs/flutter-apk/app-release.apk release/
      - uses: actions/upload-artifact@v3     # เก็บ artifact สำหรับดาวน์โหลด
        with:
          name: app-release
          path: release/
