name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  flutter_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src  # ระบุให้รันทุกคำสั่งที่โฟลเดอร์ src
    
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze code
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/coverage/lcov.info  # ต้องแก้ path ของไฟล์ coverage ด้วย
          fail_ci_if_error: true